import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import test from 'node:test';

import { DeviceJsError, translateDeviceProgram } from '../testing.mjs';

const functions = [
  {
    name: 'rotate',
    kind: 'device',
    parameters: [{ name: 'x', type: 'u32' }],
    returns: 'u32',
  },
  {
    name: 'searchKernel',
    kind: 'kernel',
    parameters: [
      { name: 'out', type: 'ptr<u32>' },
      { name: 'input', type: 'ptr<u32>' },
      { name: 'flags', type: 'ptr<u32>' },
      { name: 'n', type: 'u32' },
      { name: 'scale', type: 'f32' },
      { name: 'wide', type: 'u64' },
      { name: 'bias', type: 'i32' },
    ],
    returns: 'void',
  },
];

const source = `
function rotate(x) {
  let one = gpu.u32(1);
  return (x << one) | (x >> one);
}

function searchKernel(out, input, flags, n, scale, wide, bias) {
  let i = gpu.thread.globalX();
  let zero = gpu.u32(0);
  let one = gpu.u32(1);
  let step = gpu.u32(0);
  gpu.barrier.block();
  if (i >= n) {
    return;
  }
  let x = input[i];
  while (step < gpu.u32(3)) {
    x ^= rotate(step + one);
    step++;
  }
  let f = gpu.math.sqrt(scale);
  f = gpu.math.max(f, gpu.f32(0.5));
  out[i] = x;
  gpu.atomic.add(out, i, one);
  gpu.atomic.cas(flags, i, zero, one);
  gpu.fence.device();
}
`;

function expectDeviceCode(code) {
  return (error) => error instanceof DeviceJsError && error.code === code;
}

test('Device-JS translates structured control flow, pointer access, helpers and mixed scalar ABI deterministically', () => {
  const first = translateDeviceProgram({ source, functions });
  const second = translateDeviceProgram({ source, functions });

  assert.equal(first.contract, 'SPEC-0013-v1+SPEC-0022-atomic-observation-v1+SPEC-0022-device-publication-v1+SPEC-0014-publication-mailbox-v1');
  assert.equal(first.sha256, second.sha256);
  assert.equal(first.generatedSource, second.generatedSource);
  assert.equal(first.parser.name, 'acorn');
  assert.match(first.parser.version, /^8\./);
  assert.equal(first.kernels.length, 1);
  assert.equal(first.kernels[0].name, 'searchKernel');
  assert.equal(first.kernels[0].functionName, 'djs_kernel_0');
  assert.deepEqual(first.kernels[0].parameters, [
    { kind: 'device-memory' },
    { kind: 'device-memory' },
    { kind: 'device-memory' },
    { kind: 'u32' },
    { kind: 'f32' },
    { kind: 'u64' },
    { kind: 'i32' },
  ]);

  assert.match(first.generatedSource, /__device__ unsigned int djs_device_0\(unsigned int p0\);/);
  assert.match(first.generatedSource, /extern "C" __global__ void djs_kernel_0\(unsigned int\* p0, unsigned int\* p1, unsigned int\* p2, unsigned int p3, float p4, unsigned long long p5, int p6\)/);
  assert.match(first.generatedSource, /static_cast<unsigned int>\(\(\(blockIdx\.x \* blockDim\.x\) \+ threadIdx\.x\)\)/);
  assert.match(first.generatedSource, /while \(/);
  assert.match(first.generatedSource, /atomicAdd\(/);
  assert.match(first.generatedSource, /atomicCAS\(/);
  assert.match(first.generatedSource, /__syncthreads\(\)/);
  assert.match(first.generatedSource, /__threadfence\(\)/);
  assert.match(first.generatedSource, /sqrtf\(/);
  assert.match(first.generatedSource, /fmaxf\(/);
  assert.doesNotMatch(first.generatedSource, /#include <cuda\/atomic>/);
  assert.doesNotMatch(first.generatedSource, /searchKernel/);
  assert.doesNotMatch(first.generatedSource, /rotate\(/);
});

test('unchanged legacy Device-JS preserves its exact contract, identity and generated bytes', () => {
  const request = {
    source: 'function k(out, x) { let y = gpu.math.sqrt(x); out[gpu.u32(0)] = gpu.u32(1); }',
    functions: [{ name: 'k', kind: 'kernel', parameters: [{ name: 'out', type: 'ptr<u32>' }, { name: 'x', type: 'f32' }], returns: 'void' }],
  };
  const translated = translateDeviceProgram(request);
  assert.equal(translated.contract, 'SPEC-0013-v1+SPEC-0022-atomic-observation-v1+SPEC-0022-device-publication-v1+SPEC-0014-publication-mailbox-v1');
  assert.equal(translated.sha256, '6e07b278fbdba29a2604643a29b04f48dc66cbbe98368370902a504b62d0aa57');
  assert.equal(createHash('sha256').update(translated.generatedSource).digest('hex'), '911eab26a877714733ae3089d0b93c0445ac9a0918dd4fd2aa418ce5f5081c6a');
});

test('dense numeric Device-JS admits exact new types, casts, arithmetic and special-value math', () => {
  const translated = translateDeviceProgram({
    source: `
function dense(out64, out16, outBf16, words, x64, x16, xBf16) {
  let d = gpu.math.sqrt(x64 + gpu.f64(4));
  d = gpu.math.maximum(d, gpu.f64.negativeInfinity());
  let h = (x16 * gpu.f16(2)) + gpu.cast.f16(gpu.u32(1));
  h = gpu.math.minimum(h, gpu.f16.positiveInfinity());
  let b = gpu.math.exp(xBf16 / gpu.bf16(2));
  b = gpu.math.min(b, gpu.bf16.positiveInfinity());
  out64[gpu.u32(0)] = gpu.cast.f64(h);
  out16[gpu.u32(0)] = gpu.math.abs(h);
  outBf16[gpu.u32(0)] = -b;
  words[gpu.u32(0)] = gpu.cast.u32(gpu.f64.nan());
  if (gpu.math.isNaN(gpu.bf16.nan())) {
    words[gpu.u32(1)] = gpu.cast.u32(d);
  }
}
`,
    functions: [{
      name: 'dense',
      kind: 'kernel',
      parameters: [
        { name: 'out64', type: 'ptr<f64>' },
        { name: 'out16', type: 'ptr<f16>' },
        { name: 'outBf16', type: 'ptr<bf16>' },
        { name: 'words', type: 'ptr<u32>' },
        { name: 'x64', type: 'f64' },
        { name: 'x16', type: 'f16' },
        { name: 'xBf16', type: 'bf16' },
      ],
      returns: 'void',
    }],
  });
  assert.match(translated.contract, /SPEC-0030-dense-numeric-v1$/);
  assert.equal(translated.compile.headerProfile, 'cuda-numeric');
  assert.deepEqual(translated.kernels[0].parameters, [
    { kind: 'device-memory' }, { kind: 'device-memory' }, { kind: 'device-memory' }, { kind: 'device-memory' },
    { kind: 'f64' }, { kind: 'f16' }, { kind: 'bf16' },
  ]);
  for (const expected of [
    '#include <cuda_fp16.h>', '#include <cuda_bf16.h>', 'double* p0', '__half* p1', '__nv_bfloat16* p2',
    '__hadd_rn', '__hmul_rn', '__hdiv', '__hmin_nan', '__hmin', '__habs', '__hneg', '__hisnan',
    '__uint2half_rn', '__half2float', 'djs_sat_u32', 'djs_maximum_f64', '__ushort_as_bfloat16(0x7fc0u)',
  ]) assert(translated.generatedSource.includes(expected), `missing dense lowering ${expected}`);
});

test('dense numeric header requirements compose with scoped atomics and fail closed when contradicted', () => {
  const request = {
    source: 'function k(out, ready, x) { out[gpu.u32(0)] = gpu.math.abs(x); gpu.atomic.storeReleaseDevice(ready, gpu.u32(0), gpu.u32(1)); }',
    functions: [{ name: 'k', kind: 'kernel', parameters: [{ name: 'out', type: 'ptr<f64>' }, { name: 'ready', type: 'ptr<u32>' }, { name: 'x', type: 'f64' }], returns: 'void' }],
  };
  const translated = translateDeviceProgram(request);
  assert.equal(translated.compile.headerProfile, 'cuda-device');
  assert.match(translated.generatedSource, /#include <cuda\/atomic>/);
  assert.throws(() => translateDeviceProgram({ ...request, compile: { headerProfile: 'cuda-cccl' } }), expectDeviceCode('DEVICE_JS_NUMERIC_PROFILE_REQUIRED'));
  assert.throws(() => translateDeviceProgram({ ...request, compile: { headerProfile: 'cuda-numeric' } }), expectDeviceCode('DEVICE_JS_NUMERIC_PROFILE_REQUIRED'));
  assert.throws(() => translateDeviceProgram({
    source: 'function k(values) { gpu.atomic.add(values, gpu.u32(0), gpu.f16(1)); }',
    functions: [{ name: 'k', kind: 'kernel', parameters: [{ name: 'values', type: 'ptr<f16>' }], returns: 'void' }],
  }), expectDeviceCode('DEVICE_JS_ATOMIC_TYPE'));
});

test('floating literals remain valid and deterministic across fixed and exponential notation', () => {
  const translated = translateDeviceProgram({
    source: 'function k(out64, out32) { out64[gpu.u32(0)] = gpu.f64(1000000000000000000000); out64[gpu.u32(1)] = gpu.f64(42); out32[gpu.u32(0)] = gpu.f32(1e30); }',
    functions: [{ name: 'k', kind: 'kernel', parameters: [{ name: 'out64', type: 'ptr<f64>' }, { name: 'out32', type: 'ptr<f32>' }], returns: 'void' }],
  });
  assert.match(translated.generatedSource, /1\.0000000000000000e\+21/);
  assert.match(translated.generatedSource, /42\.0/);
  assert.match(translated.generatedSource, /1\.00000002e\+30f/);
  assert.doesNotMatch(translated.generatedSource, /e\+21\.0/);
  assert.doesNotMatch(translated.generatedSource, /e\+30\.0f/);
});

test('dense exact casts cover every admitted numeric source and destination pair', () => {
  const scalars = [
    ['u', 'u32'], ['i', 'i32'], ['l', 'u64'], ['f', 'f32'], ['d', 'f64'], ['h', 'f16'], ['b', 'bf16'],
  ];
  const outputs = scalars.map(([, type]) => [`out${type}`, `ptr<${type}>`]);
  const assignments = outputs.flatMap(([output, pointerType]) => {
    const target = pointerType.slice(4, -1);
    return scalars.map(([name], index) => `${output}[gpu.u32(${index})] = gpu.cast.${target}(${name});`);
  }).join('\n');
  const parameters = [
    ...outputs.map(([name, type]) => ({ name, type })),
    ...scalars.map(([name, type]) => ({ name, type })),
  ];
  const translated = translateDeviceProgram({
    source: `function allCasts(${parameters.map(({ name }) => name).join(', ')}) { ${assignments} }`,
    functions: [{ name: 'allCasts', kind: 'kernel', parameters, returns: 'void' }],
  });
  assert.equal(translated.compile.headerProfile, 'cuda-numeric');
  for (const expected of [
    'djs_u32_as_i32', 'djs_sat_u32', 'djs_sat_i32', 'djs_sat_u64',
    '__int2float_rn', '__uint2float_rn', '__ull2float_rn', '__double2float_rn', '__ull2double_rn',
    '__int2half_rn', '__uint2half_rn', '__ull2half_rn', '__float2half_rn', '__double2half', '__bfloat162float',
    '__int2bfloat16_rn', '__uint2bfloat16_rn', '__ull2bfloat16_rn', '__float2bfloat16_rn', '__double2bfloat16', '__half2float',
  ]) assert(translated.generatedSource.includes(expected), `missing cast lowering ${expected}`);
});

test('every dense floating kind covers arithmetic, comparison, special and math helper families', () => {
  const kinds = ['f64', 'f16', 'bf16'];
  const functions = kinds.map((kind) => ({
    name: `math_${kind}`,
    kind: 'kernel',
    parameters: [{ name: 'out', type: `ptr<${kind}>` }, { name: 'a', type: kind }, { name: 'b', type: kind }],
    returns: 'void',
  }));
  const units = kinds.map((kind) => `
function math_${kind}(out, a, b) {
  let x = a + b;
  x = x - b;
  x = x * a;
  x = x / b;
  x = -x;
  x = gpu.math.sqrt(gpu.math.abs(x));
  x = gpu.math.log(x);
  x = gpu.math.exp(x);
  x = gpu.math.min(x, b);
  x = gpu.math.max(x, b);
  x = gpu.math.minimum(x, b);
  x = gpu.math.maximum(x, b);
  if (gpu.math.isNaN(x)) { x = gpu.${kind}.nan(); }
  if (x < b) { x = gpu.${kind}.positiveInfinity(); }
  if (x <= b) { x = gpu.${kind}.negativeInfinity(); }
  if (x > b) { x = a; }
  if (x >= b) { x = b; }
  if (x === b) { x = a; }
  if (x !== b) { x = b; }
  out[gpu.u32(0)] = x;
}
`).join('\n');
  const translated = translateDeviceProgram({ source: units, functions });
  assert.equal(translated.compile.headerProfile, 'cuda-numeric');
  for (const expected of [
    'sqrt(', 'log(', 'exp(', 'fabs(', 'djs_minimum_f64', 'djs_maximum_f64',
    '__hadd_rn', '__hsub_rn', '__hmul_rn', '__hdiv', '__hneg', '__habs', '__hisnan',
    '__hmin', '__hmax', '__hmin_nan', '__hmax_nan', 'hsqrt(', 'hlog(', 'hexp(',
    '__ushort_as_half(0x7e00u)', '__ushort_as_bfloat16(0x7fc0u)',
  ]) assert(translated.generatedSource.includes(expected), `missing dense family lowering ${expected}`);
  assert.throws(() => translateDeviceProgram({
    source: 'function k(out, a, b) { out[gpu.u32(0)] = a % b; }',
    functions: [{ name: 'k', kind: 'kernel', parameters: [{ name: 'out', type: 'ptr<f64>' }, { name: 'a', type: 'f64' }, { name: 'b', type: 'f64' }], returns: 'void' }],
  }), expectDeviceCode('DEVICE_JS_OPERATOR_TYPE'));
  assert.throws(() => translateDeviceProgram({
    source: 'function k(out, a, b) { out[gpu.u32(0)] = a & b; }',
    functions: [{ name: 'k', kind: 'kernel', parameters: [{ name: 'out', type: 'ptr<bf16>' }, { name: 'a', type: 'bf16' }, { name: 'b', type: 'bf16' }], returns: 'void' }],
  }), expectDeviceCode('DEVICE_JS_OPERATOR_TYPE'));
});

test('program identity changes with semantic source, type metadata and compile inputs', () => {
  const baseline = translateDeviceProgram({ source, functions });
  const sourceChange = translateDeviceProgram({ source: `${source}\n`, functions });
  const typeChange = translateDeviceProgram({
    source,
    functions: functions.map((fn) => fn.name === 'searchKernel'
      ? { ...fn, parameters: fn.parameters.map((parameter) => parameter.name === 'bias' ? { ...parameter, type: 'u32' } : parameter) }
      : fn),
  });
  const compileChange = translateDeviceProgram({ source, functions, compile: { architecture: 'compute_80' } });

  assert.notEqual(sourceChange.sha256, baseline.sha256);
  assert.notEqual(typeChange.sha256, baseline.sha256);
  assert.notEqual(compileChange.sha256, baseline.sha256);
  assert.match(baseline.generatedName, /^device-js-[a-f0-9]{16}\.cu$/);
});

test('scoped atomic observation fails closed outside its exact profile, dtype and void context', () => {
  const metadata = [{
    name: 'k',
    kind: 'kernel',
    parameters: [{ name: 'words', type: 'ptr<u32>' }, { name: 'floats', type: 'ptr<f32>' }],
    returns: 'void',
  }];
  const compile = { headerProfile: 'cuda-cccl' };
  const accepted = translateDeviceProgram({
    source: 'function k(words, floats) { gpu.atomic.storeRelaxedDevice(words, gpu.u32(0), gpu.u32(1)); let x = gpu.atomic.loadRelaxedDevice(words, gpu.u32(0)); }',
    functions: metadata,
    compile,
  });
  assert.match(accepted.generatedSource, /#include <cuda\/atomic>/);
  assert.match(accepted.generatedSource, /cuda::atomic_ref<unsigned int, cuda::thread_scope_device>\(p0\[/);
  assert.match(accepted.generatedSource, /\.store\([^;]*, cuda::memory_order_relaxed\);/);
  assert.match(accepted.generatedSource, /\.load\(cuda::memory_order_relaxed\)/);
  assert.throws(() => translateDeviceProgram({
    source: 'function k(words, floats) { let x = gpu.atomic.loadRelaxedDevice(words, gpu.u32(0)); }',
    functions: metadata,
  }), expectDeviceCode('DEVICE_JS_ATOMIC_PROFILE_REQUIRED'));
  assert.throws(() => translateDeviceProgram({
    source: 'function k(words, floats) { let x = gpu.atomic.loadRelaxedDevice(floats, gpu.u32(0)); }',
    functions: metadata,
    compile,
  }), expectDeviceCode('DEVICE_JS_ATOMIC_TYPE'));
  assert.throws(() => translateDeviceProgram({
    source: 'function k(words, floats) { for (gpu.atomic.storeRelaxedDevice(words, gpu.u32(0), gpu.u32(1)); false; ) {} }',
    functions: metadata,
    compile,
  }), expectDeviceCode('DEVICE_JS_VOID_HELPER_CONTEXT'));
});

test('device publication helpers lower exact u32/u64 acquire and release operations and fail closed', () => {
  const metadata = [{
    name: 'k',
    kind: 'kernel',
    parameters: [
      { name: 'words', type: 'ptr<u32>' },
      { name: 'wide', type: 'ptr<u64>' },
      { name: 'floats', type: 'ptr<f32>' },
    ],
    returns: 'void',
  }];
  const compile = { headerProfile: 'cuda-cccl' };
  const accepted = translateDeviceProgram({
    source: 'function k(words, wide, floats) { gpu.atomic.storeReleaseDevice(words, gpu.u32(0), gpu.u32(7)); let x = gpu.atomic.loadAcquireDevice(words, gpu.u32(0)); gpu.atomic.storeReleaseDevice(wide, gpu.u64(0n), gpu.u64(9n)); let y = gpu.atomic.loadAcquireDevice(wide, gpu.u32(0)); }',
    functions: metadata,
    compile,
  });
  const acceptedAgain = translateDeviceProgram({
    source: 'function k(words, wide, floats) { gpu.atomic.storeReleaseDevice(words, gpu.u32(0), gpu.u32(7)); let x = gpu.atomic.loadAcquireDevice(words, gpu.u32(0)); gpu.atomic.storeReleaseDevice(wide, gpu.u64(0n), gpu.u64(9n)); let y = gpu.atomic.loadAcquireDevice(wide, gpu.u32(0)); }',
    functions: metadata,
    compile,
  });
  assert.equal(accepted.sha256, acceptedAgain.sha256);
  assert.equal(accepted.generatedSource, acceptedAgain.generatedSource);
  assert.match(accepted.generatedSource, /#include <cuda\/atomic>/);
  assert.match(accepted.generatedSource, /cuda::atomic_ref<unsigned int, cuda::thread_scope_device>\(p0\[/);
  assert.match(accepted.generatedSource, /cuda::atomic_ref<unsigned long long, cuda::thread_scope_device>\(p1\[/);
  assert.match(accepted.generatedSource, /\.store\([^;]*, cuda::memory_order_release\);/);
  assert.match(accepted.generatedSource, /\.load\(cuda::memory_order_acquire\)/);
  assert.equal([...accepted.generatedSource.matchAll(/cuda::memory_order_release/g)].length, 2);
  assert.equal([...accepted.generatedSource.matchAll(/cuda::memory_order_acquire/g)].length, 2);

  for (const request of [
    { source: 'function k(words, wide, floats) { let x = gpu.atomic.loadAcquireDevice(words, gpu.u32(0)); }', code: 'DEVICE_JS_ATOMIC_PROFILE_REQUIRED' },
    { source: 'function k(words, wide, floats) { let x = gpu.atomic.loadAcquireDevice(floats, gpu.u32(0)); }', compile, code: 'DEVICE_JS_ATOMIC_TYPE' },
    { source: 'function k(words, wide, floats) { let x = gpu.atomic.loadAcquireDevice(words, gpu.f32(0.0)); }', compile, code: 'DEVICE_JS_ATOMIC_TYPE' },
    { source: 'function k(words, wide, floats) { gpu.atomic.storeReleaseDevice(words, gpu.u32(0), gpu.u64(1n)); }', compile, code: 'DEVICE_JS_ATOMIC_TYPE' },
    { source: 'function k(words, wide, floats) { let x = gpu.atomic.loadAcquireDevice(words); }', compile, code: 'DEVICE_JS_HELPER_ARGUMENTS' },
    { source: 'function k(words, wide, floats) { for (gpu.atomic.storeReleaseDevice(words, gpu.u32(0), gpu.u32(1)); false; ) {} }', compile, code: 'DEVICE_JS_VOID_HELPER_CONTEXT' },
    { source: 'function k(words, wide, floats) { let x = gpu.atomic.loadAcquireSystem(words, gpu.u32(0)); }', compile, code: 'DEVICE_JS_HELPER_UNKNOWN' },
  ]) {
    assert.throws(() => translateDeviceProgram({ source: request.source, functions: metadata, compile: request.compile }), expectDeviceCode(request.code));
  }
});

test('publication mailbox helpers lower only direction-specific opaque u32 lanes at system scope', () => {
  const request = {
    source: 'function k(control, observation) { let value = gpu.mailbox.loadAcquireSystem(control); gpu.mailbox.storeReleaseSystem(observation, value); }',
    functions: [{ name: 'k', kind: 'kernel', parameters: [
      { name: 'control', type: 'mailbox<host-to-device,u32>' },
      { name: 'observation', type: 'mailbox<device-to-host,u32>' },
    ], returns: 'void' }],
    compile: { headerProfile: 'cuda-cccl' },
  };
  const translated = translateDeviceProgram(request);
  assert.deepEqual(translated.kernels[0].parameters, [
    { kind: 'publication-mailbox-host-to-device-u32' },
    { kind: 'publication-mailbox-device-to-host-u32' },
  ]);
  assert.match(translated.generatedSource, /thread_scope_system/);
  assert.match(translated.generatedSource, /memory_order_acquire/);
  assert.match(translated.generatedSource, /memory_order_release/);
  assert.throws(() => translateDeviceProgram({ ...request, source: 'function k(control, observation) { gpu.mailbox.storeReleaseSystem(control, gpu.u32(1)); }' }), expectDeviceCode('DEVICE_JS_MAILBOX_DIRECTION'));
  assert.throws(() => translateDeviceProgram({ ...request, compile: { headerProfile: 'none' } }), expectDeviceCode('DEVICE_JS_ATOMIC_PROFILE_REQUIRED'));
  assert.throws(() => translateDeviceProgram({ ...request, source: 'function k(control, observation) { control[gpu.u32(0)] = gpu.u32(1); }' }), expectDeviceCode('DEVICE_JS_POINTER_ACCESS_INVALID'));
});

test('Device-JS uses canonical CUDA target policy and preserves validation ownership', () => {
  const accepted = translateDeviceProgram({ source, functions, compile: { architecture: 'compute_120' } });
  assert.equal(accepted.compile.architecture, 'compute_120');
  for (const [architecture, reason] of [
    ['compute_120f', 'policy'], ['compute_120a', 'policy'], ['compute_1000', 'policy'], ['sm_120', 'prefix'], ['compute_7', 'syntax'],
  ]) {
    assert.throws(
      () => translateDeviceProgram({ source, functions, compile: { architecture } }),
      (error) => error instanceof DeviceJsError
        && error.code === 'DEVICE_JS_COMPILE_OPTIONS_INVALID'
        && error.category === 'validation'
        && error.details.reason === reason,
      architecture,
    );
  }
});

test('numeric literals require explicit scalar constructors and are range checked', () => {
  const metadata = [{ name: 'k', kind: 'kernel', parameters: [{ name: 'out', type: 'ptr<u32>' }], returns: 'void' }];
  assert.throws(() => translateDeviceProgram({ source: 'function k(out) { let x = 1; out[gpu.u32(0)] = x; }', functions: metadata }), expectDeviceCode('DEVICE_JS_LITERAL_REQUIRES_CAST'));
  assert.throws(() => translateDeviceProgram({ source: 'function k(out) { let x = gpu.u32(-1); }', functions: metadata }), expectDeviceCode('DEVICE_JS_LITERAL_RANGE'));
  assert.throws(() => translateDeviceProgram({ source: 'function k(out) { let x = gpu.u64(18446744073709551616n); }', functions: metadata }), expectDeviceCode('DEVICE_JS_LITERAL_RANGE'));
  assert.throws(() => translateDeviceProgram({ source: 'function k(out) { let x = gpu.f32(1e400); }', functions: metadata }), expectDeviceCode('DEVICE_JS_LITERAL_RANGE'));
});

test('ordinary JS coercion and unsupported language forms fail closed', () => {
  const metadata = [{ name: 'k', kind: 'kernel', parameters: [{ name: 'out', type: 'ptr<u32>' }], returns: 'void' }];
  const rejected = [
    'function k(out) { let x = {}; }',
    'function k(out) { let x = []; }',
    'function k(out) { switch (gpu.u32(1)) { default: return; } }',
    'function k(out) { try { return; } catch (e) { return; } }',
    'function k(out) { let f = () => gpu.u32(1); }',
    'function k(out) { let s = "1"; }',
    'function k(out) { out.x = gpu.u32(1); }',
    'function k(out) { for (const x of out) { return; } }',
  ];
  for (const candidate of rejected) assert.throws(() => translateDeviceProgram({ source: candidate, functions: metadata }), DeviceJsError);
});

test('metadata mismatch and static type mismatch fail before CUDA generation', () => {
  assert.throws(() => translateDeviceProgram({
    source: 'function k(x) { return; }',
    functions: [{ name: 'k', kind: 'kernel', parameters: [{ name: 'y', type: 'u32' }], returns: 'void' }],
  }), expectDeviceCode('DEVICE_JS_FUNCTION_METADATA_MISMATCH'));

  assert.throws(() => translateDeviceProgram({
    source: 'function k(out) { let x = gpu.u32(1); x = gpu.f32(1.0); }',
    functions: [{ name: 'k', kind: 'kernel', parameters: [{ name: 'out', type: 'ptr<u32>' }], returns: 'void' }],
  }), expectDeviceCode('DEVICE_JS_TYPE_MISMATCH'));
});

test('direct and indirect device recursion fail deterministically', () => {
  assert.throws(() => translateDeviceProgram({
    source: 'function f(x) { return f(x); } function k(out) { out[gpu.u32(0)] = f(gpu.u32(1)); }',
    functions: [
      { name: 'f', kind: 'device', parameters: [{ name: 'x', type: 'u32' }], returns: 'u32' },
      { name: 'k', kind: 'kernel', parameters: [{ name: 'out', type: 'ptr<u32>' }], returns: 'void' },
    ],
  }), expectDeviceCode('DEVICE_JS_RECURSION_FORBIDDEN'));

  assert.throws(() => translateDeviceProgram({
    source: 'function a(x) { return b(x); } function b(x) { return a(x); } function k(out) { out[gpu.u32(0)] = a(gpu.u32(1)); }',
    functions: [
      { name: 'a', kind: 'device', parameters: [{ name: 'x', type: 'u32' }], returns: 'u32' },
      { name: 'b', kind: 'device', parameters: [{ name: 'x', type: 'u32' }], returns: 'u32' },
      { name: 'k', kind: 'kernel', parameters: [{ name: 'out', type: 'ptr<u32>' }], returns: 'void' },
    ],
  }), expectDeviceCode('DEVICE_JS_RECURSION_FORBIDDEN'));
});

test('unknown helpers and kernel calls from device code fail closed', () => {
  assert.throws(() => translateDeviceProgram({
    source: 'function k(out) { gpu.magic(); }',
    functions: [{ name: 'k', kind: 'kernel', parameters: [{ name: 'out', type: 'ptr<u32>' }], returns: 'void' }],
  }), expectDeviceCode('DEVICE_JS_HELPER_UNKNOWN'));

  assert.throws(() => translateDeviceProgram({
    source: 'function d() { k(); return; } function k() { return; }',
    functions: [
      { name: 'd', kind: 'device', parameters: [], returns: 'void' },
      { name: 'k', kind: 'kernel', parameters: [], returns: 'void' },
    ],
  }), expectDeviceCode('DEVICE_JS_KERNEL_CALL_FORBIDDEN'));
});
